---
variables:
  BUILD_8: 'True'
  BUILD_7: 'True'
  BUILD_6: 'False'
  KOJI_TAG_7: 'ai7'
  KOJI_TAG_8: 'collectd8'
  DIST_7: '.ai7'

include: 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'

.test_install:
  script:
    - rpm -qa python*-collectd_nfsiostat --scripts | grep "condrestart"
