---
image: gitlab-registry.cern.ch/linuxsupport/c8-base

variables:
  BUILD_8: 'True'
  BUILD_7: 'True'
  BUILD_6: 'False'
  KOJI_TAG_7: 'ai7'
  KOJI_TAG_8: 'collectd8'
  DIST_7: '.ai7'
  EPEL_REPO: 'http://linuxsoft.cern.ch/epel/8/Everything/x86_64/'

include: 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'

pylint:
  stage: prebuild
  script:
    - dnf install -y --nogpgcheck yum-utils
    - yum-config-manager --add-repo $EPEL_REPO
    - yum install -y --nogpgcheck python3-pylint python3-mock
    - pylint-3 -E src/collectd_nfsiostat/__init__.py
    - PYTHONPATH=src pylint-3 -E t/*.py

nosetests:
  stage: prebuild
  script:
    - yum install -y --nogpgcheck python3-mock python3-nose
    - PYTHONPATH=src python3 -m nose t

.test_install:
  script:
    - rpm -qa python*-collectd_nfsiostat --scripts | grep "condrestart"
